import Head from 'next/head'
import Banner from '../components/Banner'
import Bannertext from '../components/Bannertext'
import Header from '../components/Header'
import Title from '../components/Title'
import styles from '../styles/Home.module.css'

export default function Home({movies}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />
      {/* banner */}
      <Banner movies={movies}  />
      <Bannertext movies={movies}/>
      <Title />
    </div>
  )
}

export async function getServerSideProps(context){
  const total = await fetch("https://api.themoviedb.org/3/trending/movie/week?api_key=bac63f0b426881aff0bc5d4cb4ed4f72").then(
    (res)=> res.json()
  );
  const movies= total.results;
  return {
    props:{
      movies
    }
  }
}